/vis/open OGL
/control/saveHistory
#/vis/viewer/set/background white
/vis/viewer/set/background white
/vis/geometry/set/colour all -1 0 0 0
/vis/drawVolume worlds
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate
#/vis/scene/add/axes
/vis/geometry/set/colour cell 0 0.5 0.5 0.5
/vis/geometry/set/forceSolid cell
/vis/geometry/set/colour cell_wrapper 0 0.1 0.5 0.5
/vis/geometry/set/forceSolid cell_wrapper
/vis/scene/add/date
/vis/scene/add/hits